import fetch from 'node-fetch';

const BACKEND_URL = 'http://localhost:3001/api/generate';

async function testIntegration() {
    console.log("🚀 Testing Local LLM Integration via Backend...");

    try {
        const response = await fetch(BACKEND_URL, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                userInput: "The knight draws his sword",
                config: {
                    genre: "Dark Fantasy",
                    tone: "Suspenseful"
                }
            })
        });

        if (!response.ok) {
            console.error(`❌ Backend Error: ${response.status} ${response.statusText}`);
            const text = await response.text();
            console.error(text);
            return;
        }

        const data = await response.json();
        console.log("✅ Success! Response received:");
        console.log("-----------------------------------------");
        console.log(data.text);
        console.log("-----------------------------------------");

        if (data.text.includes("Simulated Response")) {
            console.log("⚠️ WARNING: It seems to have fallen back to the simulation/fallback logic.");
        } else {
            console.log("🎉 Confirmed: Response generated by LLM (Local or Remote).");
        }

    } catch (error) {
        console.error("❌ Test Failed:", error.message);
    }
}

testIntegration();
