import React from 'react';
import { ArrowLeft } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { Button } from '../components/ui/Button';

const TermsOfService: React.FC = () => {
    const navigate = useNavigate();

    return (
        <div className="min-h-screen bg-slate-50 dark:bg-slate-900 transition-colors p-6 md:p-12">
            <div className="max-w-4xl mx-auto space-y-8">
                <Button variant="ghost" onClick={() => navigate(-1)} className="gap-2">
                    <ArrowLeft size={16} /> Back
                </Button>

                <div className="bg-white dark:bg-slate-800 rounded-2xl p-8 md:p-12 shadow-sm border border-slate-100 dark:border-slate-700 space-y-6">
                    <h1 className="text-3xl font-bold text-slate-900 dark:text-white">Terms of Service</h1>
                    <p className="text-slate-500 text-sm">Last updated: {new Date().toLocaleDateString()}</p>

                    <div className="space-y-4 text-slate-700 dark:text-slate-300 leading-relaxed">
                        <section>
                            <h2 className="text-xl font-semibold text-slate-900 dark:text-white mb-2">1. Acceptance of Terms</h2>
                            <p>By accessing or using Inkspire, you agree to be bound by these Terms of Service.</p>
                        </section>

                        <section>
                            <h2 className="text-xl font-semibold text-slate-900 dark:text-white mb-2">2. User Content</h2>
                            <p>You retain ownership of any content you create using our platform. However, you grant us a license to use, store, and display your content solely for the purpose of providing the service.</p>
                        </section>

                        <section>
                            <h2 className="text-xl font-semibold text-slate-900 dark:text-white mb-2">3. Acceptable Use</h2>
                            <p>You agree not to use the service to generate content that is illegal, harmful, or violates the rights of others. We reserve the right to terminate accounts that violate this policy.</p>
                        </section>

                        <section>
                            <h2 className="text-xl font-semibold text-slate-900 dark:text-white mb-2">4. Disclaimer</h2>
                            <p> The service is provided "as is" without warranties of any kind. We are not responsible for any content generated by the AI models.</p>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default TermsOfService;
